### PR TITLE
Fix "import" list_mode of vcd_resource_list data source when names have special characters

### LINKED ISSUE #1236: data vcd_resource_list with vcd_nsxv_firewall_rule is working incorrectly.
Hi, 

I found several issues while running the command data vcd_resource_list with vcd_nsxv_firewall_rule.

### Terraform Version
Terraform v1.7.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/hcp v0.84.1
+ provider registry.terraform.io/hashicorp/vault v4.1.0
+ provider registry.terraform.io/vmware/nsxt v3.5.0
+ provider registry.terraform.io/vmware/vcd v3.12.0

### Affected Resource(s)
vcd_resource_list with vcd_nsxv_firewall_rule

```
data "vcd_resource_list" "import_firewall_rules" {
  name              = "firewall-rules-list"
  org               = var.org_name
  vdc               = local.vdc_name
  resource_type     = "vcd_nsxv_firewall_rule"
  list_mode         = "import"
  import_file_name  = "import-firewall-rules.tf" 
  parent            = data.vcd_edgegateway.egw-nsxv.name
  name_id_separator = "."
}
```
The output from the generated file import-firewall-rules.tf is below

```
# Generated by vcd_resource_list - 2024-03-25T09:02:44+02:00
# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.firewall 
import {
  to = vcd_nsxv_firewall_rule.firewall-131289
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.firewall"
}

# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.dhcp 
import {
  to = vcd_nsxv_firewall_rule.dhcp-131290
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.dhcp"
}

# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.dns 
import {
  to = vcd_nsxv_firewall_rule.dns-131291
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.dns"
}

# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP1 
import {
  to = vcd_nsxv_firewall_rule.Allow_ICMP1-131090
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP1"
}

# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP 
import {
  to = vcd_nsxv_firewall_rule.Allow_ICMP-131128
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP"
}

# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic 
import {
  to = vcd_nsxv_firewall_rule.default rule for ingress traffic-131287
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic"
}
```

## 1. All generated IDs are  incorrect
Id from the generated file are 

```
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.firewall"
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.dhcp"
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.dns"
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP1"
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.Allow_ICMP"
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic"
```
id getting from the command below are different.
```
data "vcd_resource_list" "import_fw_rules_id" {
    name              = "firewall-rules-list"
    org               = var.org_name
    vdc               = local.vdc_name
    resource_type     = "vcd_nsxv_firewall_rule"
    list_mode         = "hierarchy"
    parent            = data.vcd_edgegateway.egw-nsxv.name
    name_id_separator = "."
}
output "test_test4" {
   value = data.vcd_resource_list.import_fw_rules_id
 }
```
output

```
+ test_test4          = {
      + id                = "firewall-rules-list"
      + import_file_name  = null
      + list              = [
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.firewall",
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.dhcp",
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.dns",
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.Allow_ICMP1",
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.Allow_ICMP",
          + "TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.default rule for ingress traffic",
        ]
      + list_mode         = "hierarchy"
      + name              = "firewall-rules-list"
      + name_id_separator = "."
      + name_regex        = null
      + org               = "TTO-1"
      + parent            = "TTO-1_EDGE"
      + resource_type     = "vcd_nsxv_firewall_rule"
      + vdc               = "TTO-1_oVDC"
    }

```
### Expected Behavior
it should be 
TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.firewall

### Actual Behavior
but the generated ID is
TTO-1.TTO-1_oVDC.TTO-1_EDGE.firewall

## 2. Firewall rules with spaces in their names, which also include the default rule "default rule for ingress traffic"
are processed incorrectly. Spaces should be replaced with some symbol, e.g., an underscore, as spaces are prohibited in Terraform. 

### Expected Behavior
```
# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic 
import {
  to = vcd_nsxv_firewall_rule.default rule for ingress traffic-131287
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.default_rule_for_ingress_traffic"
```
}

### Actual Behavior
```
# Import directive for vcd_nsxv_firewall_rule TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic 
import {
  to = vcd_nsxv_firewall_rule.default rule for ingress traffic-131287
  id = "TTO-1.TTO-1_oVDC.TTO-1_EDGE.default rule for ingress traffic"
}
```

### PR DESCRIPTION
**Pull request by adambarreiro**
## Problem

When any item in VCD has **a name with special characters** (` `, `%`, `$`, etc...), the data source `vcd_resource_list` does not behave correctly when `list_mode="import"` and/or there's also a file created with `import_file_name=...`.

For example, with a catalog named "f o o" and a catalog named "b%a$r":

```hcl
data "vcd_resource_list" "rs" {
  name             = "foo"
  resource_type    = "vcd_catalog"
  list_mode        = "import"
  import_file_name = "foo.txt"
}
```

In state we can see:

```
"list": [
    "terraform import vcd_catalog.f o o my-org.f o o"
    "terraform import vcd_catalog.b%a$r my-org.b%a$r"
],
```
Which is not correct, as doing

```
terraform import vcd_catalog.f o o my-org.f o o
terraform import vcd_catalog.b%a$r my-org.b%a$r
```
will fail:
- Resource names in Terraform don't have special characters, hence the `import` command will fail.
- `my-org.f o o` needs to be quoted, to consider spaces as non-arguments.
- Any shell would try to resolve `$r` and would have side effects. Same could happen with other special characters.

The file also displays:

```
import {
  to = vcd_catalog.f o o-645478e36ce8 # Incorrect
  id = "my-org.f o o"
}
```

## Fix

The correct output would be:

```
"list": [
    "terraform import vcd_catalog.f_o_o 'my-org.f o o'"
    "terraform import vcd_catalog.b_a_r 'my-org.b%a$r'"
],
```

- Any special character in the resource name is transformed into `_`, which Terraform likes.
- The VCD item identifiers are now between simple quotes, which avoids problems with spaces, `$` and other problematic characters.

The file should display:

```
import {
  to = vcd_catalog.f_o_o-645478e36ce8
  id = "my-org.f o o"
}
```

This PR fixes this behavior.

## Quirks

Having an item named "f o o" and "f$o%o" will produce the same resource name:

```
"list": [
    "terraform import vcd_catalog.f_o_o 'my-org.f o o'"
    "terraform import vcd_catalog.f_o_o 'my-org.f$o%o'"
],
```

This should be an extremely uncommon case. To fix this, we could use the VCD URN tail as the import file generation does. Not sure if it's worth it, though, as it complicates the common cases.

## Extra issue solved

When `parent` is set and the ancestors of the item are obtained, it seems the name is being repeated (like shown in Issue #1236).
ID should be `"TTO-1.TTO-1_oVDC.TTO-1_EDGE.firewall"` but in `list_mode="hierarchy"` the parent is repeated:
`TTO-1.TTO-1_oVDC.TTO-1_EDGE.TTO-1_EDGE.firewall`.

Now, hierarchy mode checks that the parent is not already present in the ancestors list, to avoid repeating it.

Simple way to reproduce:

```
data "vcd_resource_list" "r2s" {
  name          = "foo2"
  vdc           = "nsxv-vdc"
  parent        = "nsxv-gw"
  resource_type = "vcd_nsxv_firewall_rule"
  list_mode     = "hierarchy"
}
```

Without fix:
```
            "list": [
              "my-org  nsxv-vdc  nsxv-gw  nsxv-gw  firewall",
              "my-org  nsxv-vdc  nsxv-gw  nsxv-gw  default rule for ingress traffic"
            ],
```
With fix:
```
            "list": [
              "my-org  nsxv-vdc  nsxv-gw  firewall",
              "my-org  nsxv-vdc  nsxv-gw  default rule for ingress traffic"
            ],
```

## Refs

Closes #1236

### CODE REVIEW

**Review by Didainius — APPROVED** [review]
LGTM, tests pass

File: vcd/datasource_vcd_resource_list.go [hunk 1]
```diff
@@ -1158,9 +1165,15 @@ func genericResourceList(d *schema.ResourceData, resType string, ancestors []str
...
 				identifier = ref.id
 			}
-			list = append(list, fmt.Sprintf("terraform import %s.%s %s%s%s",
+			sanitizedName := ref.name
+			illegalHclNameCharsRegex := regexp.MustCompile(`[^a-zA-Z0-9_\-]+`)
+			if illegalHclNameCharsRegex.MatchString(ref.name) {
+				// Names can have special characters in VCD, but must not have in HCL resource names
+				sanitizedName = illegalHclNameCharsRegex.ReplaceAllString(ref.name, "_")
+			}
+			list = append(list, fmt.Sprintf("terraform import %s.%s '%s%s%s'",
```
Comment (lvirbalas) [inline vcd/datasource_vcd_resource_list.go:1174]: I'm a bit confused. Why do we need to quote the resource name if its name is already sanitised with underscores?

Comment (adambarreiro) [reply vcd/datasource_vcd_resource_list.go:1174]: In this case, it would not be the resource name the one in quotes, but the remote item in VCD to import (whose name cannot be changed).
For example, a catalog named _"a$b%c"_ would be `terraform import vcd_catalog.a_b_c 'a$b%c'`, where simple quotes prevent undesired side effects.
