### PR TITLE
Fix bug that causes a VApp's VM with a limited sizing policy to fail on creation when no CPU is specified

### LINKED ISSUE #875: The value for Number of CPUs must be above zero. You provided 0
Hello,

 Error: error changing cpu size: error updating VM spec section: API Error: 400: [ 5e3b99dd-f095-4622-b5d6-58a0ee5aedb7 ] The value for Number of CPUs must be above zero. You provided 0.
    │
    │   with vcd_vapp_vm.vm-webt-stack[0],
    │   on etlfme.tf line 88, in resource "vcd_vapp_vm" "vm-webt-stack":
    │   88: resource "vcd_vapp_vm" "vm-webt-stack" {

### Terraform Version
Terraform v1.1.6
on linux_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "vcd_vapp_vm" "vm-webt-stack" {

  name = format("%s%s%s%s%s%s", "etlfme", "1", "webt", "${count.index + 1}", "n", "0")

  computer_name = format("%s%s%s%s%s%s", "etlfme", "1", "webt", "${count.index + 1}", "n", "0")

  vapp_name     = "lan0etlfme1webt"
  count         = "2"
  catalog_name  = "AppLaunchPad-Catalogue"
  template_name = "ws-2019-dc-gui"


  sizing_policy_id = data.vcd_vm_sizing_policy.c_large_stack.id


  cpu_hot_add_enabled    = true
  memory_hot_add_enabled = true
  power_on               = true
  network {
    name               = "lan_prd_front"
    type               = "org"
    ip_allocation_mode = "POOL"
    is_primary         = true

  }

  metadata = {
    function = "webt"
    env      = "prd"
    zone     = "front"
    region   = "lan"
  }
  lifecycle {
    prevent_destroy = false
  }
  customization {
    force   = false
    enabled = true
    // TODO: Add windows script
    // Update Windows Administrator password
    admin_password                      = "xxxxx"
    allow_local_admin_password          = true
    auto_generate_password              = false
    must_change_password_on_first_login = true
  }


}

```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
vcd_vapp_vm.vm-webt-stack[0]: Still creating... [13m10s elapsed]
    vcd_vapp_vm.vm-fils-stack[0]: Still creating... [13m10s elapsed]
    vcd_vapp_vm.vm-appl-stack[0]: Still creating... [13m10s elapsed]
    vcd_vapp_vm.vm-webt-stack[0]: Still creating... [13m20s elapsed]
    vcd_vapp_vm.vm-fils-stack[0]: Still creating... [13m20s elapsed]
    vcd_vapp_vm.vm-appl-stack[0]: Still creating... [13m20s elapsed]
    ╷
    │ Error: error changing cpu size: error updating VM spec section: API Error: 400: [ 5e3b99dd-f095-4622-b5d6-58a0ee5aedb7 ] The value for Number of CPUs must be above zero. You provided 0.
    │
    │   with vcd_vapp_vm.vm-webt-stack[0],
    │   on etlfme.tf line 88, in resource "vcd_vapp_vm" "vm-webt-stack":
    │   88: resource "vcd_vapp_vm" "vm-webt-stack" {
    │
    ╵
    ╷
    │ Error: error changing cpu size: error updating VM spec section: API Error: 400: [ 8bbf4b03-e544-4e94-91ed-d1a7a58023a6 ] The value for Number of CPUs must be above zero. You provided 0.
    │
    │   with vcd_vapp_vm.vm-webt-stack[1],
    │   on etlfme.tf line 88, in resource "vcd_vapp_vm" "vm-webt-stack":
    │   88: resource "vcd_vapp_vm" "vm-webt-stack" {
    │
    ╵
    ╷
    │ Error: error changing cpu size: error updating VM spec section: API Error: 400: [ fe2fd24f-fe3d-45eb-9d61-e8cc07d3b010 ] The value for Number of CPUs must be above zero. You provided 0.
    │
    │   with vcd_vapp_vm.vm-appl-stack[0],
    │   on etlfme.tf line 145, in resource "vcd_vapp_vm" "vm-appl-stack":
    │  145: resource "vcd_vapp_vm" "vm-appl-stack" {

```

### Expected Behavior
create the virtual machines without errors

### Actual Behavior
It request the cpu count, but it's already accepting sizing_policy

### PR DESCRIPTION
**Pull request by adambarreiro**
## Description

This PR fixes #875.

When a Sizing Policy with limits is used to create a VM inside a VApp with `vcd_vapp_vm` resource, it should ignore `cpus`, `memory` and related attributes, as VCD picks them from the Sizing Policy itself. The same can be emulated in UI, when you have a Sizing Policy with limits, you cannot customise CPU and memory when creating a VM.

Only VM with template is affected by this issue.

## Changes

- Extended test `TestAccVcdVAppVmWithVmSizing` with extra VMs that allow to reproduce the bug.
- On creation, now the code checks whether `cpu`, `cpu_cores` or `memory` have been set. If they aren't set and the Sizing Policy contains populated properties such as CPU, CPU cores per socket and Memory, the VM doesn't trigger the `ChangeCPU` and `ChangeMemory` functions. In this case, the attributes related to these specs are retrieved from the Sizing policy by VCD and are automatically filled.

## Manual testing HCL

This snippet allows to reproduce the issue and verify the fix. Key parts are:

- VApp **template** is used
- VM is powered **ON**

```hcl
resource "vcd_vm_sizing_policy" "test-sizing-policy" {
  name        = "TestAccVcdVAppVm_SizingPolicy"
  description = "TestAccVcdVAppVm_SizingPolicy"

  cpu {
    shares                = "886"
    limit_in_mhz          = "3000"
    count                 = "1"
    speed_in_mhz          = "1000"
    cores_per_socket      = "1"
    reservation_guarantee = "0.55"
  }

  memory {
    shares                = "885"
    size_in_mb            = "1024"
    limit_in_mb           = "1024"
    reservation_guarantee = "0.3"
  }
}

resource "vcd_org_vdc" "test-vdc" {
  name        = "TestAccVcdVAppVm_SizingPolicy"
  org = "datacloud"
  description = "TestAccVcdVAppVm_SizingPolicy"
  default_vm_sizing_policy_id = vcd_vm_sizing_policy.test-sizing-policy.id
  vm_sizing_policy_ids        = [vcd_vm_sizing_policy.test-sizing-policy.id]
  
  allocation_model = "Flex"
  provider_vdc_name = "nsxTPvdc1"
  compute_capacity {
    cpu {
      allocated = 2048
    }

    memory {
      allocated = 2048
    }
  }
  storage_profile {
    name    = "*"
    limit   = 20240
    default = true
  }
  enabled                  = true
  enable_thin_provisioning = true
  enable_fast_provisioning = true
  delete_force             = true
  delete_recursive         = true
  elasticity = true
  include_vm_memory_overhead = false
}


resource "vcd_vapp" "test-vapp" {
  name = "TestAccVcdVAppVm_SizingPolicy"
  org  = "datacloud"
  vdc  = vcd_org_vdc.test-vdc.name
}

resource "vcd_vapp_vm" "test-vm" {
  org           = "datacloud"
  vdc           = vcd_org_vdc.test-vdc.name
  vapp_name     = vcd_vapp.test-vapp.name
  name          = vcd_vapp.test-vapp.name
  computer_name = "foo"
  catalog_name  = "cat-datacloud"
  template_name = "photon-hw11"
  sizing_policy_id = vcd_vm_sizing_policy.test-sizing-policy.id
}
```

## Testing

- [x] Unit test passed
- [x] Manual test with sample HCL passed
- [x] Manual test with warning case: Sizing policy has CPU defined and define `cpus` in HCL
- [x] Manual test with warning case: Sizing policy has CPU cores defined and define `cpu_count` in HCL
- [x] Manual test with warning case: Sizing policy has Memory defined and define `memory` in HCL
- [x] `vm` tag passed on VCD 10.3
- [x] `vm` tag passed on VCD 10.2

### CODE REVIEW

File: vcd/resource_vcd_vapp_vm_test.go [hunk 1]
```diff
@@ -316,3 +317,126 @@ resource "vcd_vapp_vm" "{{.VmName2}}" {
...
+
+resource "vcd_vapp_vm" "test-vm" {
+  org           = "{{.Org}}"
+  vdc           = vcd_org_vdc.test-vdc.name
+  vapp_name     = vcd_vapp.test-vapp.name
+  name          = "{{.Name}}"
+  computer_name = "foo"
+  catalog_name  = "{{.Catalog}}"
+  template_name = "{{.CatalogItem}}"
+  sizing_policy_id = vcd_vm_sizing_policy.test-sizing-policy.id
```
Comment (lvirbalas) [inline vcd/resource_vcd_vapp_vm_test.go:440]: Please add a comment explaining that the test is of NOT setting the CPU and memory - for fresh eyes it's invisible that this is what is tested. Even better, you could have those parameters but commented out + a comment explaining why.

File: vcd/resource_vcd_vapp_vm.go [hunk 2]
```diff
@@ -1238,9 +1238,14 @@ func resourceVcdVAppVmUpdateExecute(d *schema.ResourceData, meta interface{}, ex
 		}
 
 		if memoryNeedsColdChange || executionType == "create" {
-			err = vm.ChangeMemory(int64(d.Get("memory").(int)))
-			if err != nil {
-				return err
+			memory, isMemorySet := d.GetOk("memory")
+			isMemoryComingFromSizingPolicy := computePolicy != nil && (computePolicy.Memory != nil && !isMemorySet)
```
Comment (lvirbalas) [inline vcd/resource_vcd_vapp_vm.go:1242]: I'm reading the last part `&& !isMemorySet)`. Please confirm that if you do have `memory` set in VM, it works and takes precedence over the one in policy. Thanks!

File: vcd/resource_vcd_vapp_vm_test.go [hunk 3]
```diff
@@ -316,3 +317,126 @@ resource "vcd_vapp_vm" "{{.VmName2}}" {
   }
 }
 `
+
+// TestAccVcdVAppVm_SizingPolicy checks that the VApp VM is created correctly when a sizing policy with limits
+// is used in a Flex VDC and it didn't specify any CPU or Memory.
```
[the remark this answers is not in the document]
Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm_test.go]: Done, thanks!

File: vcd/resource_vcd_vapp_vm.go (hunk 2 above)
Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm.go:1242]: I'm reviewing the entire PR as this unveiled some extra use cases, as I only checked a Sizing Policy that contained all attributes set (cpu, cpu cores and memory), but when an attribute is missing, one must populate the corresponding attribute in the VM resource.

I'll add these new ones and re-test.

File: vcd/resource_vcd_vapp_vm_with_vm_sizing_test.go [hunk 4]
```diff
@@ -108,8 +111,8 @@ func TestAccVcdVAppVmWithVmSizing(t *testing.T) {
 
 					resource.TestCheckResourceAttrPair("vcd_vapp_vm."+netVmName1, "sizing_policy_id",
 						"vcd_vm_sizing_policy.size_cpu", "id"),
-					resource.TestCheckResourceAttr("vcd_vapp_vm."+netVmName1, "cpus", "3"),
-					resource.TestCheckResourceAttr("vcd_vapp_vm."+netVmName1, "cpu_cores", "3"),
+					resource.TestCheckResourceAttr("vcd_vapp_vm."+netVmName1, "cpus", "1"),
```
Comment (adambarreiro) [inline vcd/resource_vcd_vapp_vm_with_vm_sizing_test.go:114]: I lowered the CPUs here simply because of limited resources in our testing environments.

File: vcd/resource_vcd_vapp_vm_test.go (hunk 1 above)
Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm_test.go]: Done, in the new test cases (I've removed this file as we had already `resource_vcd_vapp_vm_with_vm_sizing_test.go` covering sizing policies)

**Comment by adambarreiro** [comment]
Made the changelog entry more specific.

File: vcd/resource_vcd_vapp_vm.go (hunk 2 above)
Comment (lvirbalas) [reply vcd/resource_vcd_vapp_vm.go:1242]: Did VCD throw some error in that case? The reason I'm asking is because we try to keep the code lean in these cases. Having too much logic at our level usually bites us back in the long term (as we may not know some other valid VCD use case). Maybe it's not the case here - I'm just double checking 🙂

Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm.go:1242]: No, VCD didn't throw an error. It is just that you can't do it (unless you hack the UI I guess 😄 ). I checked what happened with Terraform/API, it seems it simply ignores the CPU/Memory and uses the Sizing Policy value, without any error (i.e.: if referenced `sizing_policy_id` has 1 CPUs and `vcd_vapp_vm` has `cpus = 2`, resulting VM has 1 CPU)

Maybe I should just remove this "smart" error checks and let this go through? It seems the result is the same, and hopefully the user will know that the reason is the Sizing Policy was applied. Also what you mentioned is quite relevant.

Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm.go:1242]: Ah, the only issue is that this causes Terraform to think the VM needs an update everytime in subsequent applies:
```
resource "vcd_vapp_vm" "test-vm" {
        id                             = "urn:vcloud:vm:abc8cb18-8232-4401-b876-d3b1f5028056"
      ~ memory                         = 1024 -> 512
        name                           = "TestAccVcdVAppVm_SizingPolicy"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Comment (lvirbalas) [reply vcd/resource_vcd_vapp_vm.go:1242]: Hm, it still seems to me we should not throw a fatal error here, because VCD doesn't throw it. Here's one more thought: what about printing a warning instead?

Comment (adambarreiro) [reply vcd/resource_vcd_vapp_vm.go:1242]: Sounds good! Changed.

Comment (lvirbalas) [reply vcd/resource_vcd_vapp_vm.go:1242]: Thanks! CCing @Didainius for reviewing our decision too :)

Comment (lvirbalas) [reply vcd/resource_vcd_vapp_vm.go:1242]: Great!

**Review by Didainius — APPROVED** [review]
Thanks. I have tested this PR:
* Manually with an example built from test
* Additionally trying to change sizing policy id for 3 cases CPU+MEM, CPU only, Mem only
* Reproduced the bug with binary that was built without this patch
